# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [102]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
import timeit
a = np.ones(1000000)
b = [1 for _ in range(1000000)]
#setup_mt2 = "b = [1 for _ in range(10000)]"
setup_mt1 = """
import numpy as np
a = np.ones(100000)
"""
%time a*2
%time b*2
print("fim")
print(timeit.timeit(setup =setup_mt1, stmt = "a*2"))
#print(f'Tempo: {timeit.timeit(setup =setup_mt2, stmt = "b*2")}')

Wall time: 3.99 ms
Wall time: 6.98 ms
fim
46.52845740000021


### Exercício 2

In [ ]:
print("okay")

In [104]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
c = np.ones(10)
print(c)
c[5:8]=0
print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 0. 0. 0. 1. 1.]


### Exercício 3

In [113]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

a = np.empty((2,2,3)) #profundididade, linha, coluna -> ORDEM
print(a)
print(a[1])

[[[1.30386694e-312 2.21649092e-313 3.70188797e-313]
  [2.72560412e-312 3.06512345e-312 6.24828292e-313]]

 [[6.27969305e-299 1.01784741e-259 7.43023336e-251]
  [1.03229872e-255 1.39105403e-309 3.38460986e+125]]]
[[6.27969305e-299 1.01784741e-259 7.43023336e-251]
 [1.03229872e-255 1.39105403e-309 3.38460986e+125]]


### Exercício 4

In [38]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

c = np.empty((4,4))
print(f'Dimensões: {c.ndim}')
print(c)
c[0:2,1:3]

Dimensões: 2
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.01092457e-307]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]


array([[4.67296746e-307, 1.69121096e-306],
       [1.78022342e-306, 6.23058028e-307]])

### Exercício 5

In [42]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [50]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

len(xarr)
for i, state in enumerate(cond):
    if state:
        print(xarr[i])
    else:
        print(yarr[i])
    


1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [114]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

A = np.random.random(10)
np.save('array_a', A) # salva em formato npy
B = np.load('array_a.npy')
np.savetxt('teste.csv',A, delimiter = ',')
B = np.loadtxt('teste.csv', delimiter = ',')
print(B)


[0.44324412 0.14647497 0.10806547 0.48743168 0.82424016 0.06917545
 0.04793664 0.31929895 0.29294594 0.50744139]


### Exercício 8

In [71]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [141]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39810',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39810/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39810/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/39810/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/39810',
  'id': 807996561,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NTczMTE3MDkw',
  'number': 39810,
  'title': 'REF: put Block replace methods together',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>